# Generated by Django 6.0.6 on 2026-07-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0002_memory_created_at_memory_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
