# Generated by Django 6.0.6 on 2026-08-11 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0003_memory_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
