# Generated by Django 6.0.6 on 2026-08-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0004_memory_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
